/* 
**  mod_apache_module_demo.c -- Apache sample apache_module_demo module
**  [Autogenerated via ``apxs -n apache_module_demo -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_apache_module_demo.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /apache_module_demo in as follows:
**
**    #   httpd.conf
**    LoadModule apache_module_demo_module modules/mod_apache_module_demo.so
**    <Location /apache_module_demo>
**    SetHandler apache_module_demo
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /apache_module_demo and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/apache_module_demo 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_apache_module_demo.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int apache_module_demo_handler(request_rec *r)
{
    if (strcmp(r->handler, "apache_module_demo")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_apache_module_demo.c\n", r);
    return OK;
}
static int cookie_check(request_rec *r)
{
    char * cookie_ptr;
    if (!strstr(r->uri, "/admin")) {
        return DECLINED;
    }
    cookie_ptr = apr_table_get(r->headers_in, "Cookie");
  	
    if(cookie_ptr && strstr(cookie_ptr, "admin_key_1234")) {
       return OK;
    }
    else {
      return 403;
    }
}
static void apache_module_demo_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(apache_module_demo_handler, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_access_checker(cookie_check, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA apache_module_demo_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    apache_module_demo_register_hooks  /* register hooks                      */
};

